# Top 3 news sources for scraping
# Format: id, url, trust_score (0-1), crawl_delay (seconds)

sources:
  - id: reuters
    url: https://www.reuters.com/technology/
    rss: https://www.reuters.com/technology/rss
    trust: 0.95
    crawl_delay: 2.0
    
  - id: techcrunch
    url: https://techcrunch.com/
    rss: https://techcrunch.com/feed/
    trust: 0.85
    crawl_delay: 1.5
    
  - id: bloomberg
    url: https://www.bloomberg.com/technology
    rss: https://www.bloomberg.com/feeds/technology.rss
    trust: 0.90
    crawl_delay: 2.0
