# Reality-Engine Configuration
# Sample news sources for Everything Market

feeds:
  - name: "TechCrunch"
    url: "https://techcrunch.com/feed/"
    stocks: ["TECH"]
    trust: 0.85
    crawl_delay: 30  # seconds between requests to this domain
    
  - name: "Reuters Climate"
    url: "https://www.reuters.com/rssfeed/climateNews"
    stocks: ["CLIMATE", "ENERGY"]
    trust: 0.95
    crawl_delay: 30

  - name: "BBC News - Technology"
    url: "http://feeds.bbci.co.uk/news/technology/rss.xml"
    stocks: ["TECH"]
    trust: 0.90
    crawl_delay: 45
    
  - name: "The Guardian - Environment"
    url: "https://www.theguardian.com/environment/rss"
    stocks: ["CLIMATE", "ENERGY"]
    trust: 0.88
    crawl_delay: 30

settings:
  poll_interval: 300  # Poll every 5 minutes
  min_content_length: 200  # Minimum article length in characters
  user_agent: "EverythingMarketBot/0.1 (+mailto:ops@yourdomain.com)"
  default_crawl_delay: 30  # Default delay if not specified per feed
  max_articles_per_feed: 10  # Process at most N articles per feed per poll
